stages:
  - deploy

deploy-job:
  stage: deploy
  script:
    - cd "$CI_PROJECT_DIR/tutorial5"
    - echo "Deploy to Render production server"
    - curl -s "https://api.render.com/deploy/srv-${DEPLOY_HOOK_01}?key=${DEPLOY_HOOK_02}"
  only:
    - tutorial5