image: node:latest

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - cd "$CI_PROJECT_DIR/tutorial5"
    - npm install
  artifacts:
    paths:
      - node_modules
  only:
    - tutorial5

deploy-job:
  stage: deploy
  script:
    - cd "$CI_PROJECT_DIR/tutorial5"
    - echo "Deploy to Render production server"
    - curl -s "https://api.render.com/deploy/srv-${DEPLOY_HOOK_01}?key=${DEPLOY_HOOK_02}"
  only:
    - tutorial5